<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
        name="AutosService"
        targetNamespace="http://mijael.pe/AutosService/wsdl"
        xmlns:tns="http://mijael.pe/AutosService/wsdl"
        xmlns:ns1="http://mijael.pe/AutosService/schema"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <wsdl:types>
        <xsd:schema targetNamespace="http://mijael.pe/AutosService/wsdl" >
            <xsd:import namespace="http://mijael.pe/AutosService/schema" schemaLocation="AutosService.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="AutosRequest">
        <wsdl:part element="ns1:AutosRequest" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="AutosResponse">
        <wsdl:part element="ns1:AutosResponse" name="parameters"/>
    </wsdl:message>

    <wsdl:portType name="AutosServicePort">
        <wsdl:operation name="Autos">
            <wsdl:input message="tns:AutosRequest"/>
            <wsdl:output message="tns:AutosResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="AutosServiceSOAPBinding" type="tns:AutosServicePort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Autos">
            <soap:operation soapAction="http://mijael.pe/AutosService/Autos"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="AutosService">
        <wsdl:port binding="tns:AutosServiceSOAPBinding" name="AutosServiceSOAPBinding">
            <soap:address location="http://localhost:8080/services/soap/AutosService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>